RefreshCookie:
  name: refresh_token
  in: cookie
  required: true
  schema:
    type: string
    example: eyJhbGciOiJIUzI1NiJ9...
  description: JWT refresh token

UserAgent:
  name: User-Agent
  in: header
  required: false
  schema:
    type: string
    maxLength: 512
