name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Generate codes
        run: pnpm generate

      - name: Build package
        run: pnpm build

      - name: Push dist to release branch
        run: |
          git config user.email "ci@github.com"
          git config user.name "Github Actions"
          git add dist/ --force
          git stash
          git checkout -B release
          git stash pop
          git commit -m "Release ${{ github.ref_name }}"
          git push origin release --force
